// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Repository.Context;

namespace WebAPI.Migrations
{
    [DbContext(typeof(HospitalContext))]
    partial class HospitalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Repository.Model.TB_ATENDIMENTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClassificacaoDeRisco")
                        .HasColumnType("int");

                    b.Property<string>("Diagnostico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("HoraSaida")
                        .HasColumnType("datetime");

                    b.Property<bool>("Retorno")
                        .HasColumnType("bit");

                    b.Property<int?>("TB_FUNCIONARIOId")
                        .HasColumnType("int");

                    b.Property<int?>("TB_PACIENTEId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TB_FUNCIONARIOId");

                    b.HasIndex("TB_PACIENTEId");

                    b.ToTable("Atendimentos");
                });

            modelBuilder.Entity("WebAPI.Repository.Model.TB_ENDERECO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Rua")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("WebAPI.Repository.Model.TB_FUNCIONARIO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CRM")
                        .HasColumnType("int");

                    b.Property<int>("Cargo")
                        .HasColumnType("int");

                    b.Property<long>("Cpf")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistroGeral")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TB_ATENDIMENTOId")
                        .HasColumnType("int");

                    b.Property<int?>("TB_ENDERECOId")
                        .HasColumnType("int");

                    b.Property<int?>("TelefoneCelular")
                        .HasColumnType("int");

                    b.Property<int?>("TelefoneComercial")
                        .HasColumnType("int");

                    b.Property<int?>("TelefoneResidencial")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TB_ATENDIMENTOId");

                    b.HasIndex("TB_ENDERECOId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("WebAPI.Repository.Model.TB_MEDICAMENTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Dosagem")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int?>("TB_ATENDIMENTOId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TB_ATENDIMENTOId");

                    b.ToTable("Medicamentos");
                });

            modelBuilder.Entity("WebAPI.Repository.Model.TB_PACIENTE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Convenio")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<long>("Cpf")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistroGeral")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("TB_ATENDIMENTOId")
                        .HasColumnType("int");

                    b.Property<int?>("TB_ENDERECOId")
                        .HasColumnType("int");

                    b.Property<int?>("TelefoneCelular")
                        .HasColumnType("int");

                    b.Property<int?>("TelefoneComercial")
                        .HasColumnType("int");

                    b.Property<int?>("TelefoneResidencial")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TB_ATENDIMENTOId");

                    b.HasIndex("TB_ENDERECOId");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("WebAPI.Repository.Model.TB_ATENDIMENTO", b =>
                {
                    b.HasOne("WebAPI.Repository.Model.TB_FUNCIONARIO", "TB_FUNCIONARIO")
                        .WithMany("Atendimentos")
                        .HasForeignKey("TB_FUNCIONARIOId");

                    b.HasOne("WebAPI.Repository.Model.TB_PACIENTE", "TB_PACIENTE")
                        .WithMany("Atendimentos")
                        .HasForeignKey("TB_PACIENTEId");
                });

            modelBuilder.Entity("WebAPI.Repository.Model.TB_FUNCIONARIO", b =>
                {
                    b.HasOne("WebAPI.Repository.Model.TB_ATENDIMENTO", "TB_ATENDIMENTO")
                        .WithMany("Funcionarios")
                        .HasForeignKey("TB_ATENDIMENTOId");

                    b.HasOne("WebAPI.Repository.Model.TB_ENDERECO", "TB_ENDERECO")
                        .WithMany()
                        .HasForeignKey("TB_ENDERECOId");
                });

            modelBuilder.Entity("WebAPI.Repository.Model.TB_MEDICAMENTO", b =>
                {
                    b.HasOne("WebAPI.Repository.Model.TB_ATENDIMENTO", "TB_ATENDIMENTO")
                        .WithMany("Medicamentos")
                        .HasForeignKey("TB_ATENDIMENTOId");
                });

            modelBuilder.Entity("WebAPI.Repository.Model.TB_PACIENTE", b =>
                {
                    b.HasOne("WebAPI.Repository.Model.TB_ATENDIMENTO", "TB_ATENDIMENTO")
                        .WithMany("Pacientes")
                        .HasForeignKey("TB_ATENDIMENTOId");

                    b.HasOne("WebAPI.Repository.Model.TB_ENDERECO", "TB_ENDERECO")
                        .WithMany()
                        .HasForeignKey("TB_ENDERECOId");
                });
#pragma warning restore 612, 618
        }
    }
}
